# Redisson 配置
clusterServersConfig:
  #  pingTimeOut: 1000 最新版本已过时
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 2
  retryInterval: 1000
  dnsMonitoringInterval: 5000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  #dnsMonitoring: false
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  nodeAddresses:
    - "redis://localhost:7379"
    - "redis://localhost:7380"
    - "redis://localhost:7381"
    - "redis://localhost:7382"
    - "redis://localhost:7383"
    - "redis://localhost:7384"
## 使用org.redisson.codec.JsonJacksonCodec序列化 最新版redisson默认org.redisson.codec.MarshallingCodec
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
#  默认 NIO
#transportMode: "NIO"
threads: 16
# 默认 32 ，0表示处理器核心数*2
nettyThreads: 0
referenceEnabled: true
lockWatchdogTimeout: 30000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
